name: AGTaylor
favicon: null
layout_spectrum: 0.0697
typography_spectrum: 0.43775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fb0e06'
    - '#fdfdfd'
    - '#fa80c9'
    - '#6a6b9b'
  brandStrength: 0.625
  lightness: 0.6358205799479038
  saturation: 0.46917147538624704
  rhythmicContrast: 0.17428291658870876
purpose: []
